// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7NIMMu8U4N_h0IrY3SEoeaO1tk8cz2IM',
    appId: '1:934304345161:web:df26b52e2c475eae3be398',
    messagingSenderId: '934304345161',
    projectId: 'quanlydodacapp',
    authDomain: 'quanlydodacapp.firebaseapp.com',
    storageBucket: 'quanlydodacapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACL5le4GjxFdOaZN7JNSW_-4YYLBMlAUk',
    appId: '1:934304345161:android:c56c0b7b7c6f574a3be398',
    messagingSenderId: '934304345161',
    projectId: 'quanlydodacapp',
    storageBucket: 'quanlydodacapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlYowq2-IMi2aQfGYFqhp9j3En4XuCZFw',
    appId: '1:934304345161:ios:a70d1fa8653717863be398',
    messagingSenderId: '934304345161',
    projectId: 'quanlydodacapp',
    storageBucket: 'quanlydodacapp.firebasestorage.app',
    iosClientId: '934304345161-ge3qtne429mum76ji4pe01pbc5rcjmi1.apps.googleusercontent.com',
    iosBundleId: 'com.example.qlddDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlYowq2-IMi2aQfGYFqhp9j3En4XuCZFw',
    appId: '1:934304345161:ios:a70d1fa8653717863be398',
    messagingSenderId: '934304345161',
    projectId: 'quanlydodacapp',
    storageBucket: 'quanlydodacapp.firebasestorage.app',
    iosClientId: '934304345161-ge3qtne429mum76ji4pe01pbc5rcjmi1.apps.googleusercontent.com',
    iosBundleId: 'com.example.qlddDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7NIMMu8U4N_h0IrY3SEoeaO1tk8cz2IM',
    appId: '1:934304345161:web:b88e222804bf24943be398',
    messagingSenderId: '934304345161',
    projectId: 'quanlydodacapp',
    authDomain: 'quanlydodacapp.firebaseapp.com',
    storageBucket: 'quanlydodacapp.firebasestorage.app',
  );
}
